### ISSUE TITLE
Brak plików potrzebnych do uruchomienia projektu

### ISSUE THREAD

**Issue by michalpietron-coderslab** [medynskip/CENTRUM_DRUKU#1]
Brakuje pliku package.json przez co nie da się uruchomić projektu

**Comment by medynskip** [comment]
Projekt ma dwa pliki package.json - w folderze api i client. Blednie opsiana jest instalacja w readme.md
Poprawka w opisie uwzgledniona jest juz w branczu reduxx.
W skrócie: 
1) trzeba zrobic npm install w dwoch folderach
2) w folderze api uruchomic serwer przy pomocy 'npm run dev'
3) w folderze client uruchomic 'npm start'

**Comment by medynskip** [comment]
Solved per above comment
